import { serve } from "@hono/node-server";
import { loadEnv, loadConfig } from "./env.js";
import { createDatabase, runMigrations } from "./infrastructure/database.js";
import { createApp } from "./server.js";
import { SqliteRecordRepository } from "./infrastructure/repositories/sqlite-record.repository.js";
import { nowIso } from "./infrastructure/time.js";
import { SqliteMediaRepository } from "./infrastructure/repositories/sqlite-media.repository.js";
import { OssStorage } from "./infrastructure/oss-storage.js";
loadEnv(); const config = loadConfig(); const db = createDatabase(config.sqlitePath); await runMigrations(db);
if (!(await db.selectFrom("users").select("id").where("id", "=", "default-user").executeTakeFirst())) await db.insertInto("users").values({ id: "default-user", wx_openid: "default", created_at: nowIso() }).execute();
const oss = new OssStorage({ region: process.env.OSS_REGION ?? "oss-cn-hangzhou", bucket: process.env.OSS_BUCKET ?? "", accessKeyId: process.env.OSS_ACCESS_KEY_ID ?? "", accessKeySecret: process.env.OSS_ACCESS_KEY_SECRET ?? "" });
const server = serve({ fetch: createApp(new SqliteRecordRepository(db), new SqliteMediaRepository(db), oss, { apiKey: process.env.DASHSCOPE_API_KEY ?? "", baseUrl: process.env.DASHSCOPE_BASE_URL ?? "https://dashscope.aliyuncs.com/compatible-mode/v1" }).fetch, port: config.port, hostname: config.host });
console.log(`[main] Server listening on http://${config.host}:${config.port}`); const shutdown = async () => { server.close(); await db.destroy(); process.exit(0); }; process.on("SIGINT", shutdown); process.on("SIGTERM", shutdown);
