import { serve } from "@hono/node-server";
import { AgentHarnessManager } from "./agent/harness-manager.js";
import { loadConfig, loadEnv } from "./env.js";
import { createDatabase, runMigrations } from "./infrastructure/database.js";
import { QwenImageUnderstanding } from "./infrastructure/ai/image-understanding.js";
import { LocalMediaQueue } from "./infrastructure/local-media-queue.js";
import { LocalVectorQueue } from "./infrastructure/local-vector-queue.js";
import { OssStorage } from "./infrastructure/oss-storage.js";
import { SqliteMediaRepository } from "./infrastructure/repositories/sqlite-media.repository.js";
import { SqliteRecordRepository } from "./infrastructure/repositories/sqlite-record.repository.js";
import { nowIso } from "./infrastructure/time.js";
import { registerImageUnderstandingListener } from "./listeners/image-understanding.listener.js";
import { registerRecordVectorListener } from "./listeners/record-vector.listener.js";
import { createApp } from "./server.js";
import { logInfo } from "./infrastructure/logger.js";
import { RecordMemoryService } from "./application/memory/record-memory.js";

loadEnv(); const config = loadConfig(); const db = createDatabase(config.sqlitePath); await runMigrations(db);
if (!(await db.selectFrom("users").select("id").where("user_id", "=", "default-user").executeTakeFirst())) await db.insertInto("users").values({ user_id: "default-user", wx_openid: "default", created_at: nowIso() }).execute();
const oss = new OssStorage(config.oss);
const records = new SqliteRecordRepository(db); const media = new SqliteMediaRepository(db); const memory = new RecordMemoryService(db, config); const sessions = new AgentHarnessManager(config, memory); const queue = new LocalMediaQueue(); const vectors = new LocalVectorQueue(); const ai = { apiKey: config.dashscope.apiKey, asrBaseUrl: config.dashscope.asrBaseUrl, vlBaseUrl: config.dashscope.vlBaseUrl };
registerImageUnderstandingListener(queue, records, media, oss, new QwenImageUnderstanding(ai.apiKey, ai.vlBaseUrl));
registerRecordVectorListener(vectors, memory);
const server = serve({ fetch: createApp(records, media, queue, oss, ai, sessions, vectors).fetch, port: config.port, hostname: config.host });
logInfo("main", "Server listening", { host: config.host, port: config.port });
const shutdown = async () => { server.close(); await sessions.close(); await db.destroy(); process.exit(0); }; process.on("SIGINT", shutdown); process.on("SIGTERM", shutdown);
