import { Hono } from "hono";
import { z } from "zod";
import type { RecordRepository } from "../modules/record/record.repository.js";
import { parseSaveRecord } from "../domain/record-content.js";
import type { SqliteMediaRepository } from "../infrastructure/repositories/sqlite-media.repository.js";
import { decodeRecordCursor, encodeRecordCursor } from "../modules/record/record-cursor.js";
const body = z.object({ text: z.string(), media: z.array(z.unknown()), source: z.string().max(100).optional(), expectedVersion: z.number().int().positive().optional() }).strict();
const user = (request: Request) => request.headers.get("x-user-id") ?? "default-user";

async function view(record: any, media: SqliteMediaRepository) { const assets = await media.findMediaByIds(record.content.blocks.map((b: any) => b.mediaId), record.userId); const byId = new Map(assets.map(a => [a.id, a])); return { ...record, media: record.content.blocks.flatMap((block: any) => { const asset = byId.get(block.mediaId); if (!asset) return []; const capture = asset.extData.capture as { durationMs?: number | null } | undefined; return [{ id: asset.id, type: asset.mediaType, url: `/api/media/${asset.id}`, ...(asset.mediaType === "image" ? { description: block.description } : { durationMs: capture?.durationMs ?? null, transcriptPreview: typeof block.transcript === "string" ? block.transcript.slice(0, 200) : null }) }]; }) }; }
function responseError(c: any, result: string, current?: unknown) { if (result === "not_found") return c.json({ success: false, errorCode: "NOT_FOUND", errorMsg: "Record not found" }, 404); if (result === "conflict") return c.json({ result: current ?? null, success: false, errorCode: "VERSION_CONFLICT", errorMsg: "Record was changed by another edit" }, 409); if (result === "audio_pending") return c.json({ success: false, errorCode: "AUDIO_TRANSCRIPTION_PENDING", errorMsg: "Audio transcription is not complete" }, 409); return c.json({ success: false, errorCode: "INVALID_MEDIA", errorMsg: "Media is missing, belongs to another user, or already linked" }, 400); }

export function createRecordRoutes(records: RecordRepository, media: SqliteMediaRepository): Hono {
  const app = new Hono();
  app.post("/", async c => { const input = body.safeParse(await c.req.json().catch(() => null)); if (!input.success) return c.json({ success: false, errorCode: "INVALID_INPUT", errorMsg: input.error.message }, 400); try { const record = await records.create({ userId: user(c.req.raw), source: input.data.source, value: parseSaveRecord(input.data) }); return typeof record === "string" ? responseError(c, record) : c.json({ result: await view(record, media), success: true, errorCode: null, errorMsg: null }, 201); } catch (error) { return c.json({ success: false, errorCode: "INVALID_INPUT", errorMsg: error instanceof Error ? error.message : "Invalid record" }, 400); } });
  app.patch("/:id", async c => { const input = body.safeParse(await c.req.json().catch(() => null)); if (!input.success || !input.data.expectedVersion) return c.json({ success: false, errorCode: "INVALID_INPUT", errorMsg: "expectedVersion is required" }, 400); try { const record = await records.updateContent(c.req.param("id"), user(c.req.raw), { value: parseSaveRecord(input.data), expectedVersion: input.data.expectedVersion }); if (record === "conflict") { const current = await records.findById(c.req.param("id")); return responseError(c, record, current && current.userId === user(c.req.raw) ? await view(current, media) : null); } return typeof record === "string" ? responseError(c, record) : c.json({ result: await view(record, media), success: true, errorCode: null, errorMsg: null }); } catch (error) { return c.json({ success: false, errorCode: "INVALID_INPUT", errorMsg: error instanceof Error ? error.message : "Invalid record" }, 400); } });
  app.get("/", async c => { const cursor = c.req.query("cursor"); try { if (cursor) decodeRecordCursor(cursor); } catch { return c.json({ success: false, errorCode: "INVALID_INPUT", errorMsg: "Invalid record cursor" }, 400); } const limit = Math.min(Math.max(Number(c.req.query("limit") ?? 20), 1), 100); const rows = await records.findByUserId(user(c.req.raw), { cursor, limit: limit + 1 }); const data = await Promise.all(rows.slice(0, limit).map(record => view(record, media))); return c.json({ result: { data, hasMore: rows.length > limit, nextCursor: rows.length > limit && data.at(-1) ? encodeRecordCursor(data.at(-1)) : null, pageSize: limit }, success: true, errorCode: null, errorMsg: null }); });
  app.get("/:id", async c => { const record = await records.findById(c.req.param("id")); if (!record || record.userId !== user(c.req.raw)) return c.json({ success: false, errorCode: "NOT_FOUND", errorMsg: "Record not found" }, 404); return c.json({ result: await view(record, media), success: true, errorCode: null, errorMsg: null }); });
  return app;
}
