/** Opt-in paid integration test. Uses an isolated database/user and cleans all OSS test objects. */
import { EmbeddingsClient } from "../infrastructure/clients/embeddings-client.js";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { sql } from "kysely";
import sharp from "sharp";
import { loadConfig, loadEnv } from "../bootstrap/config.js";
import { createDatabase, runMigrations } from "../infrastructure/database/database.js";
import { OssStorage } from "../infrastructure/clients/oss-client.js";
import { CreativeImageClient, ImageClientError } from "../infrastructure/clients/creative-image-client.js";
import { RecordPostprocessQueue } from "../infrastructure/queue/record-postprocess-queue.js";
import { RecordService } from "../domain/records/index.js";
import { MediaService } from "../domain/media/index.js";
import { ProjectService, ProposalService } from "../domain/projects/index.js";
import { createAgentRuntime } from "../agent/agent-runtime.js";
import { CreativeService } from "./service.js";
import { CreativeRunner } from "./runner.js";
const live = process.env.CREATIVE_SMOKE_ALLOW_PAID === "true" && process.env.TEST_DATABASE_URL ? test : test.skip;
live("LIVE: Pi proposal-agent → accepted Proposal → Pi creator-agent → Qwen → OSS → Project", { timeout: 1_000_000 }, async () => {
  const testURL = process.env.TEST_DATABASE_URL!;
  loadEnv(); const config = loadConfig();
  const admin = createDatabase(testURL), name = `creative_live_${randomUUID().replaceAll("-", "")}`;
  await sql.raw(`CREATE DATABASE ${name}`).execute(admin);
  const url = new URL(testURL); url.pathname = `/${name}`;
  const db = createDatabase(url.href), dir = mkdtempSync(resolve(tmpdir(), "fanto-creative-live-"));
  const oss = new OssStorage(config.oss), keys = new Set<string>();
  const storage = { readUrl: oss.readUrl.bind(oss), getObject: oss.getObject.bind(oss), remove: oss.remove.bind(oss), putObject: async (key: string, data: Buffer, mime: string) => { keys.add(key); await oss.putObject(key, data, mime); } };
  const embeddings = new EmbeddingsClient(config.dashscope.apiKey, config.dashscope.baseUrl, config.dashscope.embeddingModel, config.dashscope.embeddingDimension);
  const records = RecordService.create(db, new RecordPostprocessQueue(), undefined, undefined, CreativeService.enqueueRecord), media = MediaService.create(db, storage as never), projects = ProjectService.create(db, records, media, embeddings), proposals = ProposalService.create(db, records, media, embeddings);
  const client = new CreativeImageClient(config.creative.image); let paidCalls = 0;
  const image = { generate: async (...args: Parameters<CreativeImageClient["generate"]>) => { if (++paidCalls > 1) throw new ImageClientError("IMAGE_GENERATION_REJECTED"); return client.generate(...args); }, download: client.download.bind(client) };
  const userId = randomUUID();
  const creative = new CreativeService(db, records, projects, proposals, media, image, async id => { assert.equal(id, userId); });
  const agent = createAgentRuntime({ records, media, creative, tasks: {} as never, memories: {} as never, ...config.agent, sessionDatabasePath: resolve(dir, "sessions.sqlite"), workspaceRoot: resolve(dir, "workspaces") });
  const runner = new CreativeRunner(creative, records, agent, { ...config.creative, intervalMs: 1000, proposalTimeoutMs: 180000 });
  const wait = async (check: () => Promise<boolean>, timeout: number) => { const until = Date.now() + timeout; while (Date.now() < until) { if (await check()) return; await new Promise(resolve => setTimeout(resolve, 1000)); } assert.fail("Live pipeline timed out"); };
  try {
    await runMigrations(db); const now = new Date();
    await db.insertInto("users").values({ user_id: userId, status: "active", created_at: now, updated_at: now, disabled_at: null }).execute();
    const svg = `<svg width="768" height="1024" xmlns="http://www.w3.org/2000/svg"><rect width="768" height="1024" fill="#ddebd9"/><path d="M0 700Q300 500 768 700V1024H0" fill="#6f9771"/><path d="M80 240H688L630 180H138Z" fill="#72563c"/><rect x="138" y="240" width="492" height="330" fill="#d8b989"/><rect x="170" y="260" width="40" height="420" fill="#963e33"/><rect x="558" y="260" width="40" height="420" fill="#963e33"/><ellipse cx="384" cy="400" rx="82" ry="100" fill="#efc8a5"/><path d="M300 400Q280 260 384 270Q490 270 466 400L448 330H320Z" fill="#302925"/><path d="M298 500L470 500L510 800H258Z" fill="#3d7390"/><circle cx="355" cy="396" r="6"/><circle cx="414" cy="396" r="6"/><path d="M360 445Q384 460 408 445" stroke="#963e33" fill="none" stroke-width="4"/><path d="M320 800V980M445 800V980" stroke="#302925" stroke-width="40"/></svg>`;
    const png = await sharp(Buffer.from(svg)).png().toBuffer(), mediaId = randomUUID(), key = `users/${userId}/live-test/source.png`;
    await storage.putObject(key, png, "image/png");
    await db.insertInto("media_assets").values({ media_id: mediaId, user_id: userId, object_key: key, media_type: "image", mime_type: "image/png", bytes: png.length, status: "ready", ext_data: "{}", created_at: now.toISOString(), updated_at: now.toISOString() }).execute();
    const created = await records.create(userId, { text: "这是我为园林旅行绘制的成年人物插画，我想把这段回忆变成红楼梦角色主题的图文创作。保留插画的同一人物，只改变服饰与氛围，只生成一张图片。", media: [{ mediaId }], location: { name: "大观园", latitude: 39.87, longitude: 116.35 }, eventAt: now.toISOString() });
    assert.equal(created.kind, "ok"); if (created.kind !== "ok") return;
    const recordId = created.record.id, processId = randomUUID();
    await records.claimPostprocess({ userId, recordId, version: 1, runId: processId });
    await records.completePostprocess({ userId, recordId, version: 1, runId: processId, images: [{ mediaId, description: "一幅成年人物插画。人物穿蓝色日常服装、黑色短发，站在古典园林亭子前；图中仅有一个人物。" }], audio: [] });
    runner.start();
    await wait(async () => { const state = await creative.analysisStatus(userId, recordId); if (["failed", "cancelled"].includes(state?.analysis?.status ?? "")) assert.fail(`Live proposal failed: ${state?.analysis?.errorCode}`); return state?.analysis?.status === "completed"; }, 600000);
    const analysis = await db.selectFrom("proposal_runs").selectAll().where("record_id", "=", recordId).executeTakeFirstOrThrow();
    assert.ok(analysis.proposal_id, `Expected a Proposal; got ${JSON.stringify(analysis.outcome)}`);
    const proposal = (await proposals.find(userId, analysis.proposal_id))!;
    assert.ok(proposal.content.creation?.objective); assert.equal(paidCalls, 0);
    const accepted = await proposals.accept(userId, proposal.proposalId); assert.equal(accepted.kind, "ok"); if (accepted.kind !== "ok") return;
    const projectId = accepted.data.resultProjectId;
    await wait(async () => { const run = (await creative.latest(userId, projectId))?.creation; if (run?.status === "failed") assert.fail(`Live creation failed: ${run.errorCode}`); return run?.status === "completed"; }, 900000);
    const project = (await projects.find(userId, projectId))!;
    assert.match(project.content, /fanto-media:\/\//); assert.ok(project.content.length > 100); assert.equal(paidCalls, 1);
    const assets = await media.findOwnedByIds(userId, [project.coverMediaId!]); assert.equal(assets[0]?.status, "ready");
    const output = await oss.getObject(assets[0]!.objectKey); const meta = await sharp(output).metadata(); assert.ok(meta.width && meta.height);
    console.info(JSON.stringify({ proposalCreated: true, projectPublished: true, generatedImages: paidCalls, width: meta.width, height: meta.height, markdownCharacters: project.content.length }));
  } finally {
    await runner.stop(); await agent.close(); await Promise.allSettled([...keys].map(key => oss.remove(key)));
    await db.destroy(); await sql.raw(`DROP DATABASE ${name}`).execute(admin); await admin.destroy(); rmSync(dir, { recursive: true, force: true });
  }
});
